name = "SXMag"
license = "MIT"
licenselink = "https://github.com/kawics11/hugo-sxmag/blob/master/LICENSE.md"
description = "An even more minimal magazine theme for Hugo"
homepage = "https://github.com/kawics11/hugo-sxmag"
tags = ["minimal", "magazine", "clean", "simple", "minimalist", "blog", "responsive"]
features = ["blog", "magazine"]
min_version = "0.18"

authors = [
  {name = "András Tőrös", homepage = "https://github.com/kawics11"},
  {name = "Yihui Xie", homepage = "https://yihui.org"}
]
